P8105-HW3-lj2607
================
Li Jiang
2024-10-11

``` r
#load the required packages
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(lubridate)
library(readxl)
library(stringr)
```

\#Problem1

``` r
#load the required dataset
library(p8105.datasets)
data("ny_noaa")

#view the dataset
head(ny_noaa)
```

    ## # A tibble: 6 × 7
    ##   id          date        prcp  snow  snwd tmax  tmin 
    ##   <chr>       <date>     <int> <int> <int> <chr> <chr>
    ## 1 US1NYAB0001 2007-11-01    NA    NA    NA <NA>  <NA> 
    ## 2 US1NYAB0001 2007-11-02    NA    NA    NA <NA>  <NA> 
    ## 3 US1NYAB0001 2007-11-03    NA    NA    NA <NA>  <NA> 
    ## 4 US1NYAB0001 2007-11-04    NA    NA    NA <NA>  <NA> 
    ## 5 US1NYAB0001 2007-11-05    NA    NA    NA <NA>  <NA> 
    ## 6 US1NYAB0001 2007-11-06    NA    NA    NA <NA>  <NA>

``` r
#Data cleaning
ny_noaa_df = ny_noaa %>%
  janitor::clean_names()%>%
  drop_na() %>%
  mutate(
    year = year(date), 
    month = month(date),
    day = day(date),
    tmin = as.numeric(tmin) / 10,
    tmax = as.numeric(tmax) / 10,
    prcp = as.numeric(prcp),
    snowfall = as.numeric(snow)
)

#look at the data
view(ny_noaa_df)
```

``` r
#Checking the most common value in snowfall
snowfall_distribution_plot <- ny_noaa |>
  filter(snow > 0 & snow < 100) |>
  ggplot(aes(x = factor(year), y = snow)) +
  geom_boxplot() +
  labs(
    title = "Distribution of Snowfall Values (> 0 and < 100 mm) by Year",
    x = "Year",
    y = "Snowfall (mm)"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

\*Comments: 0 is the most commonly observed value for snowfall. This
actually makes sense because it usually snows during winter, which leads
0 value to be of highest frequency in dataset.

``` r
#two-panel plot showing the average max temperature in Jan and Jul in each station across years
ny_noaa_clean <- ny_noaa_df %>%
  filter(month %in% c(1, 7)) %>% 
  select(id, year, month) %>% 
  mutate(mean_tmax = mean(ny_noaa_df$tmax, na.rm = TRUE))
```

\#Problem 2

``` r
#Import dataset accelerometer 
accelerometer <- read.csv("Problem2/nhanes_accel.csv")%>%
  janitor::clean_names()
View(accelerometer)
```

``` r
#Import dataset demographic
demo <- read.csv("Problem2/nhanes_covar.csv",skip = 4,na = c("NA", "", "."))%>%
  janitor::clean_names()
view(demo)
```

``` r
#Merge two datasets
participants <- left_join(accelerometer,demo, by = 'seqn')
view(participants)
```

``` r
#data cleaning
participants_clean <- participants %>%
  relocate(sex,age,bmi,education,.before = min1)%>%
  filter(age >= 21) %>%
  drop_na(sex,age,bmi,education)%>%
  mutate(
    sex = factor(sex, levels = c(1, 2), labels = c("Male", "Female")),
    education = factor(education, levels = c(1, 2, 3), labels = c("Less than high school", "High school equivalent", "More than high school")),
    age = as.numeric(age),
    bmi = as.numeric(bmi))
```

``` r
#table for men and women in each education category
sex_distribution <- participants_clean%>%
  group_by(education, sex) %>%
  summarize(count = n())
```

    ## `summarise()` has grouped output by 'education'. You can override using the
    ## `.groups` argument.

``` r
sex_distribution_table <- pivot_wider(
  sex_distribution,
  names_from = sex,
  values_from = count,
  values_fill = list(count = 0))

knitr::kable(sex_distribution)
```

| education              | sex    | count |
|:-----------------------|:-------|------:|
| Less than high school  | Male   |    27 |
| Less than high school  | Female |    28 |
| High school equivalent | Male   |    35 |
| High school equivalent | Female |    23 |
| More than high school  | Male   |    56 |
| More than high school  | Female |    59 |

``` r
#age distribution in each education category
age_distribution <- participants_clean%>%
  group_by(education, sex, age)%>%
  select(education, sex, age)

ggplot(age_distribution, aes(x = age, fill = sex)) +
  geom_histogram(binwidth = 5, position = "dodge", alpha = 0.7) +
  facet_wrap(~ education) +
  labs(title = "Age Distribution by Sex in Each Education Category",
       x = "Age",
       y = "Count")
```

![](P8105_HW3_LJ2607_files/figure-gfm/unnamed-chunk-11-1.png)<!-- -->

*Comments: *For the reader-friendly table: the distribution of women and
men is nearly equal in ‘less than high school’. In ‘high school
equivalent’, there are more males than females. In “more than high
school’, there are slightly more females than males. \*For age
distribution plot: The distribution of age in males and females is
nearly equal in ‘less than high school’. The overall age of females is
higher than the overall age of males and males have relatively lower
median and mean. The distribution of age by sex is nearly the same in
‘more than high school’ while the median of age in females is lower than
the the median of age in males.

``` r
#Plot total activity against age in each education category
total_activity <- participants_clean%>%
  mutate(
    total_activity = rowSums(select(., starts_with("min")), na.rm = TRUE))%>%
  relocate(total_activity,.before = min1)%>%
  select(seqn,sex,age,education,total_activity)


ggplot(total_activity, aes(x = age,y = total_activity, color = sex)) +
  geom_smooth(se = FALSE)+
  geom_point(size = 2, position = position_dodge(width = 0.5), alpha = 0.7)+
  facet_wrap(~ education) +
  labs(title = "total activity by Sex in Each Education Category",
       x = "Age",
       y = "total_activity")
```

    ## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'

![](P8105_HW3_LJ2607_files/figure-gfm/unnamed-chunk-12-1.png)<!-- -->
\*Comments: In each education category, there is a general decreasing
trend for total activity as ages increases.In the “Less than high
school” group, physical activity decreases with age for both men and
women, with some fluctuations around ages 50-60, and individual
variations are evident.

In the “High school equivalent” group, women generally have higher
activity levels than men, particularly between ages 30-50. Activity
decreases after age 40 for both sexes but increases before 40.

In the “More than high school” group, activity patterns are stable
across ages, with women typically more active than men. Activity
declines for both sexes after age 60.

``` r
#24-hour activity time course for each education level and gender
mean_min_by_sex_education <- participants_clean %>%
  group_by(sex, education) %>%
  summarise(across(starts_with("min"), mean, na.rm = TRUE))
```

    ## Warning: There was 1 warning in `summarise()`.
    ## ℹ In argument: `across(starts_with("min"), mean, na.rm = TRUE)`.
    ## ℹ In group 1: `sex = Male` and `education = Less than high school`.
    ## Caused by warning:
    ## ! The `...` argument of `across()` is deprecated as of dplyr 1.1.0.
    ## Supply arguments directly to `.fns` through an anonymous function instead.
    ## 
    ##   # Previously
    ##   across(a:b, mean, na.rm = TRUE)
    ## 
    ##   # Now
    ##   across(a:b, \(x) mean(x, na.rm = TRUE))

    ## `summarise()` has grouped output by 'sex'. You can override using the `.groups`
    ## argument.

``` r
mean_min_long <- mean_min_by_sex_education %>%
  pivot_longer(
    cols = starts_with("min"), 
    names_to = "minute", 
    names_prefix = 'min',
    values_to = 'mean'
  )%>%
  mutate(minute = as.numeric(minute))

ggplot(mean_min_long, mapping=aes(x=minute, y=mean, color=sex)) + geom_line(size=0.5) + theme_light() + facet_grid(.~ education) +
  geom_smooth(size=0.7) + scale_x_continuous(limits=c(0, 1440)) +
  scale_y_continuous(limits=c(0,18), breaks=seq(0,18, by=3)) + xlab("24-hour activity time courses") + ylab("mean acceleorometers value per minute") +
  ggtitle("Scatterplot of  the mean acceleorometers readings per minute against 24-hour activity ") + theme(legend.position = "bottom", plot.title=element_text(hjust=.5))
```

    ## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
    ## ℹ Please use `linewidth` instead.
    ## This warning is displayed once every 8 hours.
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    ## generated.

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](P8105_HW3_LJ2607_files/figure-gfm/unnamed-chunk-13-1.png)<!-- -->
\*Comments The 24-hour activity time courses are similar in each
education category with peak at 750 and lowest point at 250. Less than
high school: Both men and women have low activity levels in the early
morning (around 250min) and peak in the afternoon followed by a steady
decline until night. High school equivalent: Both men and women also
show low activity in the early morning, with peaks in the afternoon then
decrease steadily into the night. More than high school: The trend is
similar to the “High school equivalent” group, but women show
significantly higher activity levels than men during peak periods.

\#Problem3

``` r
#Import 4 datasets
Jan_2020 <- read_csv("Problem3/Jan 2020 Citi.csv",na = c("NA", "", ".","unknown"))%>%
  janitor::clean_names()%>%
  mutate(
    year = 2020, month = 'January')
```

    ## Rows: 12420 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
Jan_2024 <- read_csv("Problem3/Jan 2024 Citi.csv",na = c("NA", "", ".","unknown"))%>%
  janitor::clean_names()%>%
  mutate(
    year = 2024, month = 'January')
```

    ## Rows: 18861 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
July_2020 <- read_csv("Problem3/July 2020 Citi.csv",na = c("NA", "", ".","unknown"))%>%
  janitor::clean_names()%>%
  mutate(
    year = 2020, month = 'July')
```

    ## Rows: 21048 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
July_2024 <- read_csv("Problem3/July 2024 Citi.csv",na = c("NA", "", ".","unknown"))%>%
  janitor::clean_names()%>%
  mutate(
    year = 2024, month = 'July')
```

    ## Rows: 47156 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (6): ride_id, rideable_type, weekdays, start_station_name, end_station_n...
    ## dbl (1): duration
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
#merge 4 datasets
nyc_rider_df <- bind_rows(Jan_2020,July_2020,Jan_2024,July_2024)%>%
  relocate(year, month,.before = weekdays)
```

``` r
nrow(nyc_rider_df)
```

    ## [1] 99485

``` r
summary(nyc_rider_df)
```

    ##    ride_id          rideable_type           year         month          
    ##  Length:99485       Length:99485       Min.   :2020   Length:99485      
    ##  Class :character   Class :character   1st Qu.:2020   Class :character  
    ##  Mode  :character   Mode  :character   Median :2024   Mode  :character  
    ##                                        Mean   :2023                     
    ##                                        3rd Qu.:2024                     
    ##                                        Max.   :2024                     
    ##    weekdays            duration       start_station_name end_station_name  
    ##  Length:99485       Min.   :  1.002   Length:99485       Length:99485      
    ##  Class :character   1st Qu.:  5.595   Class :character   Class :character  
    ##  Mode  :character   Median :  9.839   Mode  :character   Mode  :character  
    ##                     Mean   : 13.930                                        
    ##                     3rd Qu.: 17.560                                        
    ##                     Max.   :238.780                                        
    ##  member_casual     
    ##  Length:99485      
    ##  Class :character  
    ##  Mode  :character  
    ##                    
    ##                    
    ## 

``` r
variable.names(nyc_rider_df)
```

    ## [1] "ride_id"            "rideable_type"      "year"              
    ## [4] "month"              "weekdays"           "duration"          
    ## [7] "start_station_name" "end_station_name"   "member_casual"

\*Description of dataset: The cleaned nyc_rider dataset contains 99485
observations and 9 variables, containing ride information in January and
July in 2020 and 2024. Key variables include
“ride_id”,“rideable_type”,“year”,“month”
“weekdays”,“duration”,“start_station_name”,“end_station_name”,“member_casual”
as indicator of member rider or casual rider status. The cleaning
process include merging four corresponding datasets and cleaning column
names.

``` r
#produce table showing total number of riders in each year and month seprating casual rider and member

total_rider <- nyc_rider_df%>%
  mutate(year_month = str_c(year,month,sep = "_"))%>%
  select(ride_id,year_month,member_casual)%>%
  group_by(year_month,member_casual)%>%
  summarize(count = n())
```

    ## `summarise()` has grouped output by 'year_month'. You can override using the
    ## `.groups` argument.

``` r
total_rider_table <- pivot_wider(
  total_rider,
  names_from = year_month,
  values_from = count)

knitr::kable(total_rider_table)
```

| member_casual | 2020_January | 2020_July | 2024_January | 2024_July |
|:--------------|-------------:|----------:|-------------:|----------:|
| casual        |          984 |      5637 |         2108 |     10894 |
| member        |        11436 |     15411 |        16753 |     36262 |

\*Comments: The dataset summarized the number of casual and member rides
for two specific time points: January and July of 2020 and 2024.

Casual users: The number of casual rides increased significantly over
time, from 984 in January 2020 to 10,894 in July 2024. There is also a
noticeable seasonal difference, with higher counts in July compared to
January in both years.

Member users: Member rides consistently outnumber casual rides,
indicating potential benefits of being member. Their numbers also grew
from 11,436 in January 2020 to 36,262 in July 2024. Similar to casual
rides, there are higher counts in July than in January each year.

Both casual and member rides increased over the years, with a clear
seasonal pattern showing higher activity in July.

``` r
#checking na in dataset July_2024
na_rows <- July_2024[!complete.cases(July_2024), ]

#Since several starting stations contain null value, I decided to drop na
July_2024_clean <- July_2024%>%
  drop_na(start_station_name)%>%
  select(ride_id,start_station_name)

#Create table showing 5 most popular starting stations for July 2024
July_2024_clean_table <- July_2024_clean%>%
  group_by(start_station_name)%>%
  summarize(count = n())%>%
  arrange(desc(count))
view(July_2024_clean_table)
```

``` r
#Create a table including day of the week,month,year, median ride duration

median_duration <- nyc_rider_df %>%
  mutate(weekdays = factor(weekdays, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))) %>%
  select(year, month, weekdays, duration) %>%
  group_by(year, month, weekdays) %>%
  summarise(median_duration = median(duration, na.rm = TRUE))
```

    ## `summarise()` has grouped output by 'year', 'month'. You can override using the
    ## `.groups` argument.

``` r
ggplot(median_duration,aes(x = weekdays, y = median_duration, group = month,color = month))+
  geom_line(aes(color = month),alpha = .5)+
  facet_grid(.~year)+
  labs(title = "Median Ride Duration by Weekday, Month, and Year",
       x = "Day of the Week",
       y = "Median Ride Duration (minutes)",
       color = "Month")+
   theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(legend.position = "bottom")
```

![](P8105_HW3_LJ2607_files/figure-gfm/unnamed-chunk-19-1.png)<!-- -->
\*Comments: The median ride duration is much higher in 2020 compared to
2024. The median ride duration in July tends to be higher than median
ride duration in January. The median ride duration tends to be higher in
weekends comparing to weekdays.

``` r
#Figure that shows the impact of month,membership status, bike type on distribution of duration in 2024

bikes_2024 <- nyc_rider_df%>%
  filter(year == 2024)%>%
  group_by(rideable_type,month,member_casual)

bikes_2024_plot <- ggplot(bikes_2024,aes(x = duration,fill = factor(member_casual))) +
  geom_histogram(binwidth =10, position = "dodge", alpha = 0.9) +
  facet_grid(month ~ rideable_type)+
     labs(
       title = "Histogram of Ride Duration by Member Status, Month, and Bike Type 2024",
       x = "Ride Duration (minutes)",
       y = "Count",
       fill = "Member_casual")

print(bikes_2024_plot)
```

![](P8105_HW3_LJ2607_files/figure-gfm/unnamed-chunk-20-1.png)<!-- -->
\*Comments: The distribution of electric bikes is higher for shorter
rides compared to classic bikes. Member tend to have higher ride
duration compared to casual rides. July has significantly more rides
compared to January. Even though casual rides have lower ride duration,
it is more spread compared to member rides.
